export const baseTechTree = () => ({
  archeryRange: {
    units: {
      archer: true,
      crossbowman: true,
      arbalester: true,
      skirmisher: true,
      eliteSkirmisher: true,
      cavalryArcher: true,
      heavyCavalryArcher: true,
      handCannoneer: true,
    },
    techs: { thumbRing: true, parthianTactics: true },
  },
  barracks: {
    units: {
      militia: true,
      manAtArms: true,
      longSwordsman: true,
      twoHandedSwordsman: true,
      champion: true,
      spearman: true,
      pikeman: true,
      halberdier: true,
      eagleScout: true,
      eagleWarrior: true,
      eliteEagleWarrior: true,
    },
    techs: { supplies: true, squires: true, arson: true },
  },
  blacksmith: {
    techs: {
      forging: true,
      ironCasting: true,
      blastFurnace: true,
      scaleMailArmor: true,
      chainMailArmor: true,
      plateMailArmor: true,
      fletching: true,
      bodkinArrow: true,
      bracer: true,
      paddedArcherArmor: true,
      leatherArcherArmor: true,
      ringArcherArmor: true,
      scaleBardingArmor: true,
      chainBardingArmor: true,
      plateBardingArmor: true,
    },
  },
  castle: {
    techs: {
      hoardings: true,
      conscription: true,
      sappers: true,
    },
  },
  dock: {
    units: {
      fishingShip: true,
      transportShip: true,
      tradeCog: true,
      galley: true,
      warGalley: true,
      galleon: true,
      fireGalley: true,
      fireShip: true,
      fastFireShip: true,
      demolitionRaft: true,
      demolitionShip: true,
      heavyDemolitionShip: true,
      cannonGalleon: true,
      eliteCannonGalleon: true,
    },
    techs: {
      gillnets: true,
      careening: true,
      dryDock: true,
      shipwright: true,
    },
  },
  lumberCamp: { techs: { doubleBitAxe: true, bowSaw: true, twoManSaw: true } },
  market: {
    techs: { caravan: true, coinage: true, banking: true, guilds: true },
  },
  mill: { techs: { horseCollar: true, heavyPlow: true, cropRotation: true } },
  miningCamp: {
    techs: {
      goldMining: true,
      goldShaftMining: true,
      stoneMining: true,
      stoneShaftMining: true,
    },
  },
  monastery: {
    techs: {
      redemption: true,
      atonement: true,
      herbalMedicine: true,
      heresy: true,
      sanctity: true,
      fervor: true,
      faith: true,
      illumination: true,
      blockPrinting: true,
      theocracy: true,
    },
  },
  stable: {
    units: {
      scoutCavalry: true,
      lightCavalry: true,
      hussar: true,
      knight: true,
      cavalier: true,
      paladin: true,
      camelRider: true,
      heavyCamelRider: true,
      battleElephant: true,
      eliteBattleElephant: true,
      steppeLancer: true,
      eliteSteppeLancer: true,
    },
    techs: { bloodlines: true, husbandry: true },
  },
  siegeWorkshop: {
    units: {
      batteringRam: true,
      cappedRam: true,
      siegeRam: true,
      mangonel: true,
      onager: true,
      siegeOnager: true,
      scorpion: true,
      heavyScorpion: true,
      bombardCannon: true,
      siegeTower: true,
    },
  },
  townCenter: {
    techs: {
      townWatch: true,
      townPatrol: true,
      wheelbarrow: true,
      handCart: true,
      loom: true,
      feudalAge: true,
      castleAge: true,
      imperialAge: true,
    },
  },
  university: {
    techs: {
      treadmillCrane: true,
      masonry: true,
      architecture: true,
      ballistics: true,
      heatedShot: true,
      murderHoles: true,
      arrowslits: true,
      chemistry: true,
      siegeEngineers: true,
    },
  },
});

export type TechTree = ReturnType<typeof baseTechTree>;
